<a href="https://colab.research.google.com/github/tantai17132002/DH/blob/main/bt_day5_tang_cuong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
V = np.zeros((3,4))

In [3]:
V
lock = [(1,1)]

In [4]:
reward = 0

In [5]:
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  list_move = [up, down, left, right]

  true_list_move = []
  for move in list_move:
    for stt,i in enumerate(move):
      if i < 0:
        break
      elif i >= shape_v[stt]:
        break
      if stt:
        true_list_move.append(move)
  return true_list_move

In [7]:
moves = find_move(1,2, V.shape)

In [8]:
for l in lock:
  if l in moves:
    moves.remove(l)

In [9]:
moves

[(0, 2), (2, 2), (1, 3)]

In [10]:
V[1,3]=-1
V[0,3] = 1
V[1,1] = -100
gamma = 0.9

In [11]:
V

array([[   0.,    0.,    0.,    1.],
       [   0., -100.,    0.,   -1.],
       [   0.,    0.,    0.,    0.]])

In [12]:
moves_02 = find_move(0,2, V.shape)

In [13]:
list_a = [1,2,3]

In [14]:
def other_points(input_value, list_point):
    list_a = []
    if input_value in list_point:
        for item in list_point:
            if item != input_value:
                list_a.append(item)
    else:
        print("Giá trị nhập không hợp lệ.")
    return list_a

In [15]:
value_range = []
for move in moves_02:
  move_2, move_3 = other_points(move,moves_02)
  value = 0.8*(reward + gamma*V[move]+(0.2/len(moves_02))*(2*reward + gamma*(V[move_2]+V[move_3])))
  value_range.append(value)

In [16]:
max(value_range)

0.7200000000000001

In [17]:
V[0,2] = max(value_range)

In [18]:
V

array([[   0.  ,    0.  ,    0.72,    1.  ],
       [   0.  , -100.  ,    0.  ,   -1.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ]])