<a href="https://colab.research.google.com/github/tantai17132002/DH/blob/main/tantai_tangcuong_day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
import pandas as pd
import sys

In [63]:
np.set_printoptions(threshold=sys.maxsize)

In [64]:
v = np.zeros((6,12))

In [65]:
v

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
lock = [(0,4),(0,8),(1,4),(1,6),(1,8),(2,1),(2,2),(2,4),(2,6),(2,8),(3,1),(3,6),(3,8),(4,1),(4,2),(4,3),(4,4),(4,5),(4,6),(4,8),(4,9),(5,4)]
done = lock + [(0,11),(1,11)]

In [39]:
reward = 0

In [74]:
for l in lock: #-10: không thể đi
  v[l] = -10

In [67]:
v[0,11]= 1
v[1,11] = -1
gamma = 0.9
print(v)

[[  0.   0.   0.   0. -10.   0.   0.   0. -10.   0.   0.   1.]
 [  0.   0.   0.   0. -10.   0. -10.   0. -10.   0.   0.  -1.]
 [  0. -10. -10.   0. -10.   0. -10.   0. -10.   0.   0.   0.]
 [  0. -10.   0.   0.   0.   0. -10.   0. -10.   0.   0.   0.]
 [  0. -10. -10. -10. -10. -10. -10.   0. -10. -10.   0.   0.]
 [  0.   0.   0.   0. -10.   0.   0.   0.   0.   0.   0.   0.]]


In [68]:
def find_move(x,y, shape_v):
  up = (x-1, y)
  down = (x+1, y)
  left = (x, y-1)
  right = (x, y+1)

  list_move = [up, down, left, right]

  true_list_move = []
  for move in list_move:
    for stt,i in enumerate(move):
      if i < 0:
        break
      elif i >= shape_v[stt]:
        break
      if stt:
        true_list_move.append(move)
  for l in lock:
    if l in true_list_move:
      true_list_move.remove(l)
  return true_list_move

In [69]:
moves = find_move(0,7, v.shape)
moves

[(1, 7), (0, 6)]

In [70]:
moves_02 = find_move(0,2, v.shape)
moves_02

[(1, 2), (0, 1), (0, 3)]

In [71]:
def other_points(input_value, list_point):
    list_a = []
    if input_value in list_point:
        for item in list_point:
            if item != input_value:
                list_a.append(item)
    else:
        print("Giá trị nhập không hợp lệ.")
    return list_a

In [72]:
def update_value(moves):
  value_range = []
  for move in moves:
    position_other_points = other_points(move,moves)
    sum_other_points = 0
    for position in position_other_points:
      point = v[position]
      sum_other_points+=point
    if (len(moves)-1):
      value = 0.8*(reward + gamma*v[move])+(0.2/(len(moves)-1))*(2*reward + gamma*sum_other_points)
      value_range.append(value)
    else:
      value = reward + gamma*v[move]
      value_range.append(value)
  return max(value_range)

In [73]:
for stt in range(10):
  print(f"lần lặp: {stt+1}")
  for i, row in enumerate(v):
    for j, _ in enumerate(row):
      if (i,j) not in done:
        moves = find_move(i,j, v.shape)
        v[i,j] = update_value(moves)
  rounded_array = np.round(v, 4)
  np.set_printoptions(suppress=True)

  display(pd.DataFrame(rounded_array))

lần lặp: 1


0     1     2     3     4     5     6    7     8     9       10      11
0  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.0 -10.0   0.0  0.7200  1.0000
1  0.0   0.0   0.0   0.0 -10.0   0.0 -10.0  0.0 -10.0   0.0  0.4584 -1.0000
2  0.0 -10.0 -10.0   0.0 -10.0   0.0 -10.0  0.0 -10.0   0.0  0.3300  0.1476
3  0.0 -10.0   0.0   0.0   0.0   0.0 -10.0  0.0 -10.0   0.0  0.2376  0.1844
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0 -10.0  0.0 -10.0 -10.0  0.1711  0.1482
5  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.0   0.0   0.0  0.1232  0.1288

lần lặp: 2


0     1     2     3     4     5     6    7     8        9       10      11
0  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.0 -10.0   0.5184  0.8079  1.0000
1  0.0   0.0   0.0   0.0 -10.0   0.0 -10.0  0.0 -10.0   0.4145  0.5664 -1.0000
2  0.0 -10.0 -10.0   0.0 -10.0   0.0 -10.0  0.0 -10.0   0.3281  0.4506  0.2510
3  0.0 -10.0   0.0   0.0   0.0   0.0 -10.0  0.0 -10.0   0.2790  0.3625  0.2969
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0 -10.0  0.0 -10.0 -10.0000  0.2854  0.2511
5  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.0   0.0   0.0887  0.2251  0.2213

lần lặp: 3


0     1     2     3     4     5     6    7        8        9       10  \
0  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.0 -10.0000   0.6563  0.8300   
1  0.0   0.0   0.0   0.0 -10.0   0.0 -10.0  0.0 -10.0000   0.5530  0.5978   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0 -10.0  0.0 -10.0000   0.4639  0.4951   
3  0.0 -10.0   0.0   0.0   0.0   0.0 -10.0  0.0 -10.0000   0.3992  0.4154   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0 -10.0  0.0 -10.0000 -10.0000  0.3419   
5  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.0   0.0639   0.1736  0.2817   

       11  
0  1.0000  
1 -1.0000  
2  0.2932  
3  0.3480  
4  0.3013  
5  0.2676

lần lặp: 4


0     1     2     3     4     5     6      7        8        9       10  \
0  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.000 -10.0000   0.6972  0.8366   
1  0.0   0.0   0.0   0.0 -10.0   0.0 -10.0  0.000 -10.0000   0.5975  0.6079   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0 -10.0  0.000 -10.0000   0.5107  0.5108   
3  0.0 -10.0   0.0   0.0   0.0   0.0 -10.0  0.000 -10.0000   0.4425  0.4357   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0 -10.0  0.000 -10.0000 -10.0000  0.3662   
5  0.0   0.0   0.0   0.0 -10.0   0.0   0.0  0.046   0.1332   0.2268  0.3082   

       11  
0  1.0000  
1 -1.0000  
2  0.3091  
3  0.3687  
4  0.3225  
5  0.2877

lần lặp: 5


0     1     2     3     4     5        6       7        8        9   \
0  0.0   0.0   0.0   0.0 -10.0   0.0   0.0000  0.0000 -10.0000   0.7099   
1  0.0   0.0   0.0   0.0 -10.0   0.0 -10.0000  0.0000 -10.0000   0.6118   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0 -10.0000  0.0000 -10.0000   0.5263   
3  0.0 -10.0   0.0   0.0   0.0   0.0 -10.0000  0.0000 -10.0000   0.4574   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0 -10.0000  0.0331 -10.0000 -10.0000   
5  0.0   0.0   0.0   0.0 -10.0   0.0   0.0331  0.1019   0.1816   0.2546   

       10      11  
0  0.8386  1.0000  
1  0.6111 -1.0000  
2  0.5163  0.3149  
3  0.4433  0.3765  
4  0.3759  0.3308  
5  0.3195  0.2957

lần lặp: 6


0     1     2     3     4        5        6       7        8        9   \
0  0.0   0.0   0.0   0.0 -10.0   0.0000   0.0000  0.0000 -10.0000   0.7139   
1  0.0   0.0   0.0   0.0 -10.0   0.0000 -10.0000  0.0000 -10.0000   0.6164   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0000 -10.0000  0.0000 -10.0000   0.5314   
3  0.0 -10.0   0.0   0.0   0.0   0.0000 -10.0000  0.0238 -10.0000   0.4624   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0000 -10.0000  0.0776 -10.0000 -10.0000   
5  0.0   0.0   0.0   0.0 -10.0   0.0298   0.0787  0.1449   0.2094   0.2677   

       10      11  
0  0.8393  1.0000  
1  0.6122 -1.0000  
2  0.5182  0.3170  
3  0.4460  0.3794  
4  0.3796  0.3341  
5  0.3240  0.2989

lần lặp: 7


0     1     2     3     4        5        6       7        8        9   \
0  0.0   0.0   0.0   0.0 -10.0   0.0000   0.0000  0.0000 -10.0000   0.7152   
1  0.0   0.0   0.0   0.0 -10.0   0.0000 -10.0000  0.0000 -10.0000   0.6179   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0000 -10.0000  0.0172 -10.0000   0.5331   
3  0.0 -10.0   0.0   0.0   0.0   0.0000 -10.0000  0.0590 -10.0000   0.4641   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0000 -10.0000  0.1149 -10.0000 -10.0000   
5  0.0   0.0   0.0   0.0 -10.0   0.0709   0.1171  0.1716   0.2236   0.2736   

       10      11  
0  0.8395  1.0000  
1  0.6126 -1.0000  
2  0.5188  0.3177  
3  0.4469  0.3805  
4  0.3810  0.3355  
5  0.3259  0.3002

lần lặp: 8


0     1     2     3     4        5        6       7        8        9   \
0  0.0   0.0   0.0   0.0 -10.0   0.0000   0.0000  0.0000 -10.0000   0.7156   
1  0.0   0.0   0.0   0.0 -10.0   0.0000 -10.0000  0.0124 -10.0000   0.6184   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0000 -10.0000  0.0447 -10.0000   0.5337   
3  0.0 -10.0   0.0   0.0   0.0   0.0000 -10.0000  0.0908 -10.0000   0.4647   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0000 -10.0000  0.1399 -10.0000 -10.0000   
5  0.0   0.0   0.0   0.0 -10.0   0.1053   0.1425  0.1864   0.2305   0.2761   

       10      11  
0  0.8395  1.0000  
1  0.6127 -1.0000  
2  0.5190  0.3180  
3  0.4473  0.3809  
4  0.3816  0.3360  
5  0.3266  0.3007

lần lặp: 9


0     1     2     3     4        5        6       7        8        9   \
0  0.0   0.0   0.0   0.0 -10.0   0.0000   0.0000  0.0089 -10.0000   0.7158   
1  0.0   0.0   0.0   0.0 -10.0   0.0000 -10.0000  0.0338 -10.0000   0.6185   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0000 -10.0000  0.0714 -10.0000   0.5339   
3  0.0 -10.0   0.0   0.0   0.0   0.0000 -10.0000  0.1136 -10.0000   0.4649   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0000 -10.0000  0.1547 -10.0000 -10.0000   
5  0.0   0.0   0.0   0.0 -10.0   0.1283   0.1573  0.1941   0.2337   0.2772   

       10      11  
0  0.8396  1.0000  
1  0.6127 -1.0000  
2  0.5191  0.3180  
3  0.4474  0.3810  
4  0.3818  0.3362  
5  0.3269  0.3009

lần lặp: 10


0     1     2     3     4        5        6       7        8        9   \
0  0.0   0.0   0.0   0.0 -10.0   0.0000   0.0064  0.0255 -10.0000   0.7158   
1  0.0   0.0   0.0   0.0 -10.0   0.0000 -10.0000  0.0560 -10.0000   0.6186   
2  0.0 -10.0 -10.0   0.0 -10.0   0.0000 -10.0000  0.0919 -10.0000   0.5339   
3  0.0 -10.0   0.0   0.0   0.0   0.0000 -10.0000  0.1279 -10.0000   0.4650   
4  0.0 -10.0 -10.0 -10.0 -10.0 -10.0000 -10.0000  0.1627 -10.0000 -10.0000   
5  0.0   0.0   0.0   0.0 -10.0   0.1416   0.1652  0.1978   0.2352   0.2777   

       10      11  
0  0.8396  1.0000  
1  0.6128 -1.0000  
2  0.5191  0.3181  
3  0.4474  0.3811  
4  0.3818  0.3363  
5  0.3270  0.3010